#!/usr/bin/env bash

git flow init -d

git config --local core.bare false
git config --local core.eol lf
git config --local core.filemode true
git config --local core.ignorecase false
git config --local core.logallrefupdates true
git config --local core.repositoryformatversion 0

git config --local gitflow.branch.master main
git config --local gitflow.branch.develop develop
git config --local gitflow.prefix.bugfix bugfix-
git config --local gitflow.prefix.feature feature-
git config --local gitflow.prefix.release release-
git config --local gitflow.prefix.hotfix hotfix-
git config --local gitflow.prefix.support support-
git config --local gitflow.prefix.versiontag "v"


CWD=`pwd`
git config gitflow.path.hooks "${CWD/%dev}.git/hooks"

echo
